### ISSUE TITLE
Wrapper around igraph::all_simple_paths()

### ISSUE THREAD

**Issue by loreabad6** [luukvdmeer/sfnetworks#105]
**Is your feature request related to a problem? Please describe.**
The [`igraph::all_simple_paths()`](https://igraph.org/r/doc/all_simple_paths.html) function allows to calculate all simple paths from one set of nodes to another, but we do not support this with sfnetworks yet. 

> A path is simple if the vertices it visits are not visited more than once.

The result of this function could be useful to calculate all possible paths and not only shortest paths. However this is computationally exhausting for big networks if the paths are calculated from one "from" node to all the other nodes in the network. There was a [request to igraph to implement a `cutoff` argument to the function](https://github.com/igraph/igraph/issues/774), but [it does not seem to be implemented yet for R](https://github.com/igraph/igraph/pull/1232#issuecomment-684080274). I would suggest waiting until this parameter is implemented so that we can do some tests and then implement this feature.

**Describe the solution you'd like**
A wrapper around `igraph::all_simple_paths()` which could be implemented within `st_network_paths()` with an extra argument like `type = 'simple` for example, but we might reconsider this for future releases.

**Describe alternatives you've considered**
Currently an `sfnetwork` object can be passed directly to the igraph function by using node indices, but not `sf` objects with `POINT` geometry. 

``` r
library(sfnetworks)
library(igraph)
library(dplyr)

net = as_sfnetwork(roxel) %>% 
  activate('edges') %>% 
  mutate(weight = edge_length()) 

all_simple_paths(net, from = 1, to = c(12, 98))
#> [[1]]
#> + 20/701 vertices, from 519f8a8:
#>  [1]   1 645 481 263 164 165 441 422 486 149 150 337 351 329 657 512 506 111 524
#> [20]  98
#> 
#> [[2]]
#> + 32/701 vertices, from 519f8a8:
#>  [1]   1 645 481 263 164 165 441 422 486 149 150 337 351 329 657 512 506 111 524
#> [20] 292 167 305 446 447 445 604 444 461 468 688  11  12
#> 
#> [[3]]
#> + 25/701 vertices, from 519f8a8:
#>  [1]   1 645 481 263 164 165 441 422 486 149 150 337 351 329 657 512 506 363 535
#> [20] 513 560 203 111 524  98
#> 
#> [[4]]
#> + 37/701 vertices, from 519f8a8:
#>  [1]   1 645 481 263 164 165 441 422 486 149 150 337 351 329 657 512 506 363 535
#> [20] 513 560 203 111 524 292 167 305 446 447 445 604 444 461 468 688  11  12
#> 
#> [[5]]
#> + 34/701 vertices, from 519f8a8:
#>  [1]   1 645 481 263 164 165 441 422 486 149 379 384 206 373 372 487 359 275 432
#> [20] 277 278 352 355 345 150 337 351 329 657 512 506 111 524  98
#> 
#> [[6]]
#> + 46/701 vertices, from 519f8a8:
#>  [1]   1 645 481 263 164 165 441 422 486 149 379 384 206 373 372 487 359 275 432
#> [20] 277 278 352 355 345 150 337 351 329 657 512 506 111 524 292 167 305 446 447
#> [39] 445 604 444 461 468 688  11  12
#> 
#> [[7]]
#> + 39/701 vertices, from 519f8a8:
#>  [1]   1 645 481 263 164 165 441 422 486 149 379 384 206 373 372 487 359 275 432
#> [20] 277 278 352 355 345 150 337 351 329 657 512 506 363 535 513 560 203 111 524
#> [39]  98
#> 
#> [[8]]
#> + 51/701 vertices, from 519f8a8:
#>  [1]   1 645 481 263 164 165 441 422 486 149 379 384 206 373 372 487 359 275 432
#> [20] 277 278 352 355 345 150 337 351 329 657 512 506 363 535 513 560 203 111 524
#> [39] 292 167 305 446 447 445 604 444 461 468 688  11  12
#> 
#> [[9]]
#> + 15/701 vertices, from 519f8a8:
#>  [1]   1 645 481 263 164 208 426 424 533 657 512 506 111 524  98
#> 
#> [[10]]
#> + 27/701 vertices, from 519f8a8:
#>  [1]   1 645 481 263 164 208 426 424 533 657 512 506 111 524 292 167 305 446 447
#> [20] 445 604 444 461 468 688  11  12
#> 
#> [[11]]
#> + 20/701 vertices, from 519f8a8:
#>  [1]   1 645 481 263 164 208 426 424 533 657 512 506 363 535 513 560 203 111 524
#> [20]  98
#> 
#> [[12]]
#> + 32/701 vertices, from 519f8a8:
#>  [1]   1 645 481 263 164 208 426 424 533 657 512 506 363 535 513 560 203 111 524
#> [20] 292 167 305 446 447 445 604 444 461 468 688  11  12
```

**Comment by luukvdmeer** [comment]
Interesting, I did not know about this function before. Maybe we can restructure the `st_network_paths` by removing the `all` argument and instead add a `type` argument which can be set to `'shortest'`, `'all_shortest'` and `'all_simple'`. Depending on this argument the corresponding igraph function (either `shortest_paths`, `all_shortest_paths` or `all_simple_paths`) is called.

The cutoff would be nice to have, but I don't think we need to implement this ourselves. I would like to rely as much as possible on what igraph offers. Once they implement it for R, we use it, and otherwise not. I would argue that you can already limit the search by not including all nodes of the network in the `to` argument,  but instead subsetting them by `to = which(with_graph(net, node_distance_from(x)) < d)` (i.e. using network distance) or `to = which(with_graph(net, node_is_within_distance(x, d))` (i.e. using as-the-crow-flies distance).

**Comment by luukvdmeer** [comment]
Pushed to master as part of a new minor version. Be aware that calculation can be very slow when there are many possible paths (e.g. with multiple 'to' nodes or in large, dense networks), but this is something that 1) makes sense 2) is rather an igraph issue than an sfnetworks issue since we just wrap the igraph function.
