### ISSUE TITLE
Calculating City Circulation Plans

### ISSUE THREAD

**Issue by awjreynolds** [luukvdmeer/sfnetworks#13]
Circulation plans are grids of Low Traffic Neighbourhoods used to keep motorised traffic on main roads.

“Low traffic neighbourhoods” are groups of residential streets, bordered by main or “distributor” roads (the places where buses, lorries, non-local traffic should be), where “through” motor vehicle traffic is discouraged or removed.”

Many cities and towns are now implementing circulation plans. Is there a way to automatically identify main roads (e.g. google traffic), identify LTNs, and then identify the optimal central placements of a road blocks/bus gates for each LTN?

If not can an area be defined as an LTN and the optimal road blocks identified?
![EQfDDYFXUAAh-Nh](https://user-images.githubusercontent.com/1948692/74239070-0429a200-4ccf-11ea-8ce0-5530e84db2ff.jpeg)

Creating circulation plans for cities and towns is going to be a key for urban planning for the next 10+ years.

**Comment by mpadge** [comment]
@awjreynolds This is great and important idea, for which i've just set up [this repository](https://github.com/atfutures-labs/LTN) - empty right now, but should fill up soon.

> Is there a way to automatically identify main roads ~~(e.g. google traffic)~~

- yes

> identify LTNs

- yes, although a definitively non-trivial exercise

> then identify the optimal central placements of a road blocks/bus gates for each LTN?

yes, once the above has been done, that stage is relatively less non-trivial (but only *relatively*).

In summary, all do-able, and clearly pretty critically important. My Q for you (@awjreynolds), @Robinlovelace, @agila5, @luukvdmeer, and any others is how involved you would like and/or be able to be? I note @loreabad6 that you've tagged this as a hackathon issue, but my thoughts for now would be that this would be an appropriate single task for a singularly focussed hackathon, but otherwise would likely be too large and challenging to be able to develop any useful solutions within a matter of hours. I would nevertheless very much like to be proven wrong on that, so feel free to ignore those concerns.

Any and all interested parties please step across to the [dedicated repo](https://github.com/atfutures-labs/LTN) for continued discussions.

**Comment by Robinlovelace** [comment]
Looks good and sounds like a project that is larger than can be done in the hackathon, so the new repo could be an ideal place to develop ideas, code and results related to the issue. A narrower and more dev-focussed topic could be sfnetworks/dodgr integration, comparison, documentation ; )

**Comment by awjreynolds** [comment]
I'll just add that I would be an observer only. I simply do not have the time.

**Comment by Robinlovelace** [comment]
Existing method: https://twitter.com/awjre/status/1271698435155079171

**Comment by mpadge** [comment]
A bit of further context: that's the result of [this] (https://londonlivingstreets.files.wordpress.com/2018/09/lcc021-low-traffic-neighbourhoods-detail-v9.pdf) methodology

**Comment by Robinlovelace** [comment]
There doesn't seem to be much of a methodology there, but very useful info pack.

**Comment by luukvdmeer** [comment]
Since the hackathon is now behind us, I will close the hackathon issues. For this topic now there is a dedicated repo: https://github.com/atfutures-labs/LTN 

Personally of course I would be interested to see if and how `sfnetworks` as a package/data structure fits in there, and look forward to receiving specific feature requests ;)
