### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by eracle** [luukvdmeer/sfnetworks#15]
Hello there! 
First of all, thanks for this library.
I was wondering, what's its licence?
Regards

**Comment by Robinlovelace** [comment]
TBC.

**Comment by luukvdmeer** [comment]
The current version of sfnetworks (which is the master branch of this repository) has a GPL-2 license. However, we are developing a new version of sfnetworks in a separate branch. This branch contains a license file: https://github.com/luukvdmeer/sfnetworks/blob/develop/LICENSE

**Comment by Robinlovelace** [comment]
This raises a wider question: should issues be closed when fixed in the `develop` or `master` branch? Given that most people will download the project from the master branch by default, I suggest we start the convention of only closing issues when they are fixed on master, encouraging frequent dev -> master PRs. 

Sound reasonable @luukvdmeer ? I see a danger of the master branch stagnating if we're overly reticent.

**Comment by luukvdmeer** [comment]
@Robinlovelace yes, that sounds reasonable indeed! Let's do that.

(although for this specific question it is answered also for the current master branch by pointing to the GPL-2 license that is stated in the [DESCRIPTION](https://github.com/luukvdmeer/sfnetworks/blob/master/DESCRIPTION) file, plus mentioning that in the next release the license will change?)

**Comment by Robinlovelace** [comment]
Great, yes the issue seems fixed, good to have that protocol, only close issues when closed on master. FYI we discussed this at length in the PCT issue tracker, e.g.: https://github.com/npct/pct-shiny/issues

Makes sense to only close things when they are 'deployed'. Github does this automagically when you send a commit e.g. titled

```
Add license, close #15
```

It will only close the issue when merged to master.
